databases:
  - name: resume-analyser-db
    plan: free
    region: oregon
    databaseName: resume_analyser_production
    user: resume_analyser

services:
  - type: redis
    name: resume-analyser-redis
    region: oregon
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow all

  - type: web
    name: resume-analyser-api
    env: ruby
    region: oregon
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow all
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec puma -C config/puma.rb
    healthCheckPath: /up
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: resume-analyser-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: resume-analyser-redis
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: SECRET_KEY_BASE
        sync: false
      - key: WEB_CONCURRENCY
        value: "2"
      - key: RAILS_MAX_THREADS
        value: "5"
      - key: DEVISE_JWT_SECRET_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SIDEKIQ_USERNAME
        sync: false
      - key: SIDEKIQ_PASSWORD
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: RUN_DB_PREPARE
        value: "true"
      - key: RUN_DB_SEED
        value: "false"

  - type: worker
    name: resume-analyser-sidekiq
    env: ruby
    region: oregon
    plan: starter
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec sidekiq -C config/sidekiq.yml
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: resume-analyser-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: resume-analyser-redis
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: SECRET_KEY_BASE
        sync: false
      - key: DEVISE_JWT_SECRET_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: RUN_DB_PREPARE
        value: "false"
      - key: RUN_DB_SEED
        value: "false"
